blank_issues_enabled: false
contact_links:
  - name: 💡 Have an idea for a new feature?
    url: https://github.com/jef/stargazer-vanity/discussions
    about: Create a new idea discussion!
  - name: 🙇 Need help with stargazer-vanity?
    url: https://github.com/jef/stargazer-vanity/discussions
    about: Create a new help discussion if it hasn't been asked before!
