name: cd
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v2.13.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: stargazer-vanity
      - name: Retrieve latest tag
        run: echo "TAG=$(cat version.txt)" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Build release assets
        run: make dist
      - name: Upload Windows asset
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./stargazer-vanity.exe
          asset_name: svg-windows-amd64.exe
          asset_content_type: application/octet-stream
      - name: Upload Linux asset
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./stargazer-vanity.linux
          asset_name: svg-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload macOS asset
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./stargazer-vanity.darwin
          asset_name: svg-darwin-amd64
          asset_content_type: application/octet-stream
